### ISSUE TITLE
Portuguese translations

### ISSUE THREAD

**Issue by hugok79** [elementary/switchboard-plug-security-privacy#101]
Some text still appears in English although the Portuguese is 100% translated.
See image below
![Screeshot](https://user-images.githubusercontent.com/16929048/78906049-c2bb3600-7a76-11ea-8e2d-526974f1c4e3.png)

**Comment by danrabbit** [comment]
As far as I can tell, POTFILES is up to date and the translation does exist in the .po files included in the latest release. So these translations should be present in the released version of the plug. Not sure what the issue is

**Comment by hugok79** [comment]
Both texts have Singular an Plural translations....

**Comment by danrabbit** [comment]
It’s using ngettext so it’s intentional that there are translations for singular and plural to match the numbers in view

**Comment by hugok79** [comment]
Yes i know, but in this case could be what is causing the translations not to appear?

**Comment by tintou** [comment]
There is a know issue when ngettext is used within a plugin system, I'll provide the right workaround when I get some time.

**Comment by hugok79** [comment]
Thanks. The bugs really exist to be reported, only then the software and elementary OS has evolved

**Comment by hugok79** [comment]
That was quick! Thanks @tintou
