### ISSUE TITLE
Boot Partition has reached its limit, I wish to have an automatic cleanup

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [elementary/switchboard-plug-security-privacy#106]
or a solution that is more appropriate. A solution where users do not have to use the terminal to know & handle autoremove commands.

I guess, that due to the regular kernel image updates, 90% of my boot partition is now filled. I received a desktop notification during my last update.
I wonder how self-explanatory this notification is for everyday users. It doesn't offer me any options for what I can do or informs me about the consequences if I don't react at times.

Somehow the issue doesn't fit with Security & Privacy, does it?
However, since the housekeeping function is also located here, I can't think of any other place where the ticket could fit in well. Please feel free to move it to a more suitable place!

**Comment by cassidyjames** [comment]
I agree it makes sense to clean up unused kernels, but I don't think this makes sense here; it should be automatic, instead.
