### ISSUE TITLE
Filter isn't working

### ISSUE THREAD

**Issue by btd1337** [elementary/switchboard-plug-security-privacy#45]
The field Filter application not return any result.

![captura de tela de 2018-05-23 13 27 55](https://user-images.githubusercontent.com/11943860/40438132-a863c904-5e8d-11e8-869a-bab120dd8532.png)

![captura de tela de 2018-05-23 13 27 29](https://user-images.githubusercontent.com/11943860/40438133-a8a0d3ee-5e8d-11e8-8018-715c4a28510e.png)

![captura de tela de 2018-05-23 13 27 12](https://user-images.githubusercontent.com/11943860/40438134-a8e256e8-5e8d-11e8-8ec9-4ccd90a85e73.png)

**Comment by danrabbit** [comment]
I believe this was fixed in #46
