### ISSUE TITLE
Cannot Drag and Drop from the host 

### ISSUE THREAD

**Issue by celener** [elementary/switchboard-plug-security-privacy#58]
Hi,

Tried a lot of options to use drag and drop option from host system to Elementary OS, but no success. 

As far as i know, there is no such a problem in Ubuntu's latest version. 

It would be great if there is such an option.

Thanks

**Comment by arshubham** [comment]
@celener Can you be more clear what you mean by Drag and Drop in this context?

**Comment by danrabbit** [comment]
Closing as "Incomplete" since we never got enough information from the OP to reproduce the issue
