### ISSUE TITLE
switchboard-plug-security-privacy causes Wingpanel to Segfault

### ISSUE THREAD

**Issue by crispycookies** [elementary/switchboard-plug-security-privacy#65]
The Security Privacy Manager caused both Plank and Wingpanel to suddenly disappear after an Update.
By launching it manually, i found out, it was related to some SEGFAULT. I couldnt figure out where or when it happens.

What solved my Problem was to uninstall the Security Privacy Manager.
`sudo apt remove switchboard-plug-security-privacy`

It´s very hard for me to give further information on the issue, as I switched to arch linux with kde recently. Even if i reinstalled elementary, it is very unlikely, that it occurs again.

**Comment by arshubham** [comment]
@crispycookies Are you still experiencing the issue? I am unable to reproduce it. Please reopen if you are still getting the segfault.
